mitsubishi_arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: j1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: j2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: j3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: j4
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: j5
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: j6
    pid: {p: 100.0, i: 0.01, d: 10.0}

  # Trajectory Controllers ---------------------------------------
  mitsubishi_arm_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
    gains:
      j1:
        p: 100.0
        i: 10.0
        d: 50.0
      j2:
        p: 100.0
        i: 10.0
        d: 50.0
      j3:
        p: 100.0
        i: 10.0
        d: 50.0
      j4:
        p: 100.0
        i: 10.0
        d: 50.0
      j5:
        p: 100.0
        i: 10.0
        d: 50.0
      j6:
        p: 100.0
        i: 10.0
        d: 50.0
    constraints:
      goal_time: 100.0                   # Override default
      j1:
        trajectory: 0.01
      j2:
        trajectory: 0.01
      j3:
        trajectory: 0.01
      j4:
        trajectory: 0.01
      j5:
        trajectory: 0.01
      j6:
        trajectory: -1.0

