base_marker_id: Channel703
head_marker_id: Channel704
freq: 50
kp_x: 0.05
kp_y: 0.05
kp_z: 0.0
kp_roll: 0.0
kp_pitch: 0.0
kp_yaw: 0.0
kd_x: 0.01
kd_y: 0.01
kd_z: 0.0
kd_roll: 0.0
kd_pitch: 0.0
kd_yaw: 0.0
ki_x: 0.0
ki_y: 0.0
ki_z: 0.0
ki_roll: 0.0
ki_pitch: 0.0
ki_yaw: 0.0
