controller_list:
 - name: /mitsubishi_barrett/mitsubishi_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
 - name: /mitsubishi_barrett/barrett_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - finger_1_med_joint
      - finger_2_med_joint
      - finger_3_med_joint
      - finger_1_prox_joint
      - finger_2_prox_joint

