joint_limits:
  finger_2_med_joint:
    has_velocity_limits: true
    max_velocity: 0.01
    has_acceleration_limits: false
    max_acceleration: 0
  finger_1_prox_joint:
    has_velocity_limits: true
    max_velocity: 0.01
    has_acceleration_limits: false
    max_acceleration: 0
  finger_2_prox_joint:
    has_velocity_limits: true
    max_velocity: 0.01
    has_acceleration_limits: false
    max_acceleration: 0
  j1:
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: false
    max_acceleration: 0
  j6:
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: false
    max_acceleration: 0
  j3:
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: false
    max_acceleration: 0
  finger_3_med_joint:
    has_velocity_limits: true
    max_velocity: 0.01
    has_acceleration_limits: false
    max_acceleration: 0
  j5:
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: false
    max_acceleration: 0
  j2:
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: false
    max_acceleration: 0
  j4:
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: false
    max_acceleration: 0
  finger_1_med_joint:
    has_velocity_limits: true
    max_velocity: 0.01
    has_acceleration_limits: false
    max_acceleration: 0