<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="mitsubishi_arm">
  <property name="table_y_length" value="1.0" />
  <property name="camera_table_y_offset" value="0.265" />
  <property name="camera_table_x_offset" value="1.0" />

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find mitsubishi_arm_description)/urdf/mitsubishi_rv_6sdl_arm.gazebo" />

  <!-- Import Rviz colors -->
  <xacro:include filename="$(find mitsubishi_arm_description)/urdf/materials.xacro" />

  <!-- ros_control plugin -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/mitsubishi_arm</robotNamespace>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="gazebo_ros_joint_trajectory" filename="libgazebo_ros_joint_pose_trajectory.so">
      <robotNamespace>/mitsubishi_arm</robotNamespace>
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
    </plugin>
  </gazebo>


  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
  </joint>  

  <!-- LINKS   -->  
  <xacro:include filename="$(find mitsubishi_arm_description)/urdf/mitsubishi_rv_6sdl_arm.xacro" />

  <!-- Kinect -->
  <xacro:include filename="$(find mitsubishi_arm_description)/urdf/sensors.xacro" />


  <link name="arm_to_kinect">
  </link>

  <joint name="arm_camera" type="fixed">
    <parent link="base_link"/>
    <child link="arm_to_kinect"/>
    <origin xyz="0.50 ${table_y_length/2.0 + camera_table_y_offset} 0" rpy="0 0 0"/>
  </joint>
</robot>

